import { IconCogwheel, IconCrossCircle, IconPen } from 'hds-react';

import {
  OrganizationFormFields,
  WebStoreAccountFormFields,
  WebStoreMerchantFormFields,
} from './types';

export const TEST_PUBLISHER_ID = 'publisher:1';
export const EXTERNAL_PUBLISHER_ID = 'others';
export const KASKO_ORGANIZATION_ID = 'ahjo:u420300';

export const MAX_OGRANIZATIONS_PAGE_SIZE = 1000;

export enum ORGANIZATION_ACTIONS {
  CREATE = 'create',
  DELETE = 'delete',
  EDIT = 'edit',
  UPDATE = 'update',
}

export enum ORGANIZATION_FINANCIAL_INFO_ACTIONS {
  MANAGE_IN_CREATE = 'manage_in_create',
  MANAGE_IN_UPDATE = 'manage_in_update',
}

export const ORGANIZATION_ACTION_ICONS = {
  [ORGANIZATION_ACTIONS.CREATE]: <IconPen aria-hidden={true} />,
  [ORGANIZATION_ACTIONS.DELETE]: <IconCrossCircle aria-hidden={true} />,
  [ORGANIZATION_ACTIONS.EDIT]: <IconCogwheel aria-hidden={true} />,
  [ORGANIZATION_ACTIONS.UPDATE]: <IconPen aria-hidden={true} />,
};

export const ORGANIZATION_ACTION_LABEL_KEYS = {
  [ORGANIZATION_ACTIONS.CREATE]: 'common.save',
  [ORGANIZATION_ACTIONS.DELETE]: 'organization.form.buttonDelete',
  [ORGANIZATION_ACTIONS.EDIT]: 'organizationsPage.actionButtons.edit',
  [ORGANIZATION_ACTIONS.UPDATE]: 'common.save',
};

export enum ORGANIZATION_FIELDS {
  ADMIN_USERS = 'adminUsers',
  AFFILIATED_ORGANIZATIONS = 'affiliatedOrganizations',
  CLASSIFICATION = 'classification',
  DATA_SOURCE = 'dataSource',
  DISSOLUTION_DATE = 'dissolutionDate',
  FINANCIAL_ADMIN_USERS = 'financialAdminUsers',
  FOUNDING_DATE = 'foundingDate',
  ID = 'id',
  INTERNAL_TYPE = 'internalType',
  NAME = 'name',
  ORIGIN_ID = 'originId',
  PARENT_ORGANIZATION = 'parentOrganization',
  REGISTRATION_ADMIN_USERS = 'registrationAdminUsers',
  REGULAR_USERS = 'regularUsers',
  REPLACED_BY = 'replacedBy',
  SUB_ORGANIZATIONS = 'subOrganizations',
  WEB_STORE_ACCOUNTS = 'webStoreAccounts',
  WEB_STORE_MERCHANTS = 'webStoreMerchants',
}

export enum WEB_STORE_ACCOUNT_FIELDS {
  ACTIVE = 'active',
  BALANCE_PROFIT_CENTER = 'balanceProfitCenter',
  COMPANY_CODE = 'companyCode',
  ID = 'id',
  INTERNAL_ORDER = 'internalOrder',
  MAIN_LEDGER_ACCOUNT = 'mainLedgerAccount',
  NAME = 'name',
  OPERATION_AREA = 'operationArea',
  PROFIT_CENTER = 'profitCenter',
  PROJECT = 'project',
}

export enum WEB_STORE_MERCHANT_FIELDS {
  ACTIVE = 'active',
  BUSINESS_ID = 'businessId',
  CITY = 'city',
  EMAIL = 'email',
  ID = 'id',
  MERCHANT_ID = 'merchantId',
  NAME = 'name',
  PAYTRAIL_MERCHANT_ID = 'paytrailMerchantId',
  PHONE_NUMBER = 'phoneNumber',
  STREET_ADDRESS = 'streetAddress',
  TERMS_OF_SERVICE_URL = 'termsOfServiceUrl',
  ZIPCODE = 'zipcode',
}

export enum ORGANIZATION_INTERNAL_TYPE {
  NORMAL = 'normal',
  AFFILIATED = 'affiliated',
}

export const WEB_STORE_ACCOUNT_INITIAL_VALUES: WebStoreAccountFormFields = {
  [WEB_STORE_ACCOUNT_FIELDS.ACTIVE]: true,
  [WEB_STORE_ACCOUNT_FIELDS.BALANCE_PROFIT_CENTER]: '',
  [WEB_STORE_ACCOUNT_FIELDS.COMPANY_CODE]: '',
  [WEB_STORE_ACCOUNT_FIELDS.ID]: null,
  [WEB_STORE_ACCOUNT_FIELDS.INTERNAL_ORDER]: '',
  [WEB_STORE_ACCOUNT_FIELDS.MAIN_LEDGER_ACCOUNT]: '',
  [WEB_STORE_ACCOUNT_FIELDS.NAME]: '',
  [WEB_STORE_ACCOUNT_FIELDS.OPERATION_AREA]: '',
  [WEB_STORE_ACCOUNT_FIELDS.PROFIT_CENTER]: '',
  [WEB_STORE_ACCOUNT_FIELDS.PROJECT]: '',
};

export const WEB_STORE_MERCHANT_INITIAL_VALUES: WebStoreMerchantFormFields = {
  [WEB_STORE_MERCHANT_FIELDS.ACTIVE]: true,
  [WEB_STORE_MERCHANT_FIELDS.BUSINESS_ID]: '',
  [WEB_STORE_MERCHANT_FIELDS.CITY]: '',
  [WEB_STORE_MERCHANT_FIELDS.EMAIL]: '',
  [WEB_STORE_MERCHANT_FIELDS.ID]: null,
  [WEB_STORE_MERCHANT_FIELDS.MERCHANT_ID]: '',
  [WEB_STORE_MERCHANT_FIELDS.NAME]: '',
  [WEB_STORE_MERCHANT_FIELDS.PAYTRAIL_MERCHANT_ID]: '',
  [WEB_STORE_MERCHANT_FIELDS.PHONE_NUMBER]: '',
  [WEB_STORE_MERCHANT_FIELDS.STREET_ADDRESS]: '',
  [WEB_STORE_MERCHANT_FIELDS.TERMS_OF_SERVICE_URL]: '',
  [WEB_STORE_MERCHANT_FIELDS.ZIPCODE]: '',
};

export const ORGANIZATION_INITIAL_VALUES: OrganizationFormFields = {
  [ORGANIZATION_FIELDS.ADMIN_USERS]: [],
  [ORGANIZATION_FIELDS.AFFILIATED_ORGANIZATIONS]: [],
  [ORGANIZATION_FIELDS.CLASSIFICATION]: '',
  [ORGANIZATION_FIELDS.DATA_SOURCE]: '',
  [ORGANIZATION_FIELDS.DISSOLUTION_DATE]: null,
  [ORGANIZATION_FIELDS.FINANCIAL_ADMIN_USERS]: [],
  [ORGANIZATION_FIELDS.FOUNDING_DATE]: null,
  [ORGANIZATION_FIELDS.ID]: '',
  [ORGANIZATION_FIELDS.INTERNAL_TYPE]: ORGANIZATION_INTERNAL_TYPE.NORMAL,
  [ORGANIZATION_FIELDS.NAME]: '',
  [ORGANIZATION_FIELDS.ORIGIN_ID]: '',
  [ORGANIZATION_FIELDS.PARENT_ORGANIZATION]: '',
  [ORGANIZATION_FIELDS.REGISTRATION_ADMIN_USERS]: [],
  [ORGANIZATION_FIELDS.REGULAR_USERS]: [],
  [ORGANIZATION_FIELDS.REPLACED_BY]: '',
  [ORGANIZATION_FIELDS.SUB_ORGANIZATIONS]: [],
  [ORGANIZATION_FIELDS.WEB_STORE_ACCOUNTS]: [],
  [ORGANIZATION_FIELDS.WEB_STORE_MERCHANTS]: [],
};

export const AUTHENTICATION_NOT_NEEDED = [ORGANIZATION_ACTIONS.EDIT];

export const ORGANIZATION_COMBOBOX_FIELDS = [
  ORGANIZATION_FIELDS.ADMIN_USERS,
  ORGANIZATION_FIELDS.CLASSIFICATION,
  ORGANIZATION_FIELDS.FINANCIAL_ADMIN_USERS,
  ORGANIZATION_FIELDS.INTERNAL_TYPE,
  ORGANIZATION_FIELDS.PARENT_ORGANIZATION,
  ORGANIZATION_FIELDS.REGISTRATION_ADMIN_USERS,
  ORGANIZATION_FIELDS.REGULAR_USERS,
  ORGANIZATION_FIELDS.REPLACED_BY,
];

export const ACCOUNT_TEXT_FIELD_MAX_LENGTH = {
  [WEB_STORE_ACCOUNT_FIELDS.BALANCE_PROFIT_CENTER]: 10,
  [WEB_STORE_ACCOUNT_FIELDS.COMPANY_CODE]: 4,
  [WEB_STORE_ACCOUNT_FIELDS.INTERNAL_ORDER]: 10,
  [WEB_STORE_ACCOUNT_FIELDS.MAIN_LEDGER_ACCOUNT]: 6,
  [WEB_STORE_ACCOUNT_FIELDS.NAME]: 255,
  [WEB_STORE_ACCOUNT_FIELDS.OPERATION_AREA]: 6,
  [WEB_STORE_ACCOUNT_FIELDS.PROFIT_CENTER]: 7,
  [WEB_STORE_ACCOUNT_FIELDS.PROJECT]: 16,
};

export const ORGANIZATION_TEXT_FIELD_MAX_LENGTH = {
  [ORGANIZATION_FIELDS.ORIGIN_ID]: 255,
  [ORGANIZATION_FIELDS.NAME]: 255,
};

export const MERCHANT_TEXT_FIELD_MAX_LENGTH = {
  [WEB_STORE_MERCHANT_FIELDS.BUSINESS_ID]: 9,
  [WEB_STORE_MERCHANT_FIELDS.CITY]: 50,
  [WEB_STORE_MERCHANT_FIELDS.EMAIL]: 254,
  [WEB_STORE_MERCHANT_FIELDS.NAME]: 100,
  [WEB_STORE_MERCHANT_FIELDS.PAYTRAIL_MERCHANT_ID]: 100,
  [WEB_STORE_MERCHANT_FIELDS.PHONE_NUMBER]: 18,
  [WEB_STORE_MERCHANT_FIELDS.STREET_ADDRESS]: 500,
  [WEB_STORE_MERCHANT_FIELDS.TERMS_OF_SERVICE_URL]: 200,
  [WEB_STORE_MERCHANT_FIELDS.ZIPCODE]: 10,
};
