import { RegistrationFormFields } from './types';

export enum REGISTRATION_FIELDS {
  AUDIENCE_MAX_AGE = 'audienceMaxAge',
  AUDIENCE_MIN_AGE = 'audienceMinAge',
  CONFIRMATION_MESSAGE = 'confirmationMessage',
  ENROLMENT_END_TIME = 'enrolmentEndTime',
  ENROLMENT_START_TIME = 'enrolmentStartTime',
  INSTRUCTIONS = 'instructions',
  MAXIMUM_ATTENDEE_CAPACITY = 'maximumAttendeeCapacity',
  MINIMUM_ATTENDEE_CAPACITY = 'minimumAttendeeCapacity',
  WAITING_ATTENDEE_CAPACITY = 'waitingAttendeeCapacity',
}

export const REGISTRATION_INITIAL_VALUES: RegistrationFormFields = {
  [REGISTRATION_FIELDS.AUDIENCE_MAX_AGE]: '',
  [REGISTRATION_FIELDS.AUDIENCE_MIN_AGE]: '',
  [REGISTRATION_FIELDS.CONFIRMATION_MESSAGE]: '',
  [REGISTRATION_FIELDS.ENROLMENT_END_TIME]: null,
  [REGISTRATION_FIELDS.ENROLMENT_START_TIME]: null,
  [REGISTRATION_FIELDS.INSTRUCTIONS]: '',
  [REGISTRATION_FIELDS.MAXIMUM_ATTENDEE_CAPACITY]: '',
  [REGISTRATION_FIELDS.MINIMUM_ATTENDEE_CAPACITY]: '',
  [REGISTRATION_FIELDS.WAITING_ATTENDEE_CAPACITY]: '',
};
