#
# Test pipeline. Run build and deploy for Platta test environments.
# Pipeline runs different tests e.g. unittest and browser tests.
#
# Continuous integration (CI) triggers cause a pipeline to run whenever you push 
# an update to the specified branches or you push specified tags.
# only PR trigger pipeline
trigger: none

schedules: 
# Every hour from 7 - 24 (finnish time winter time)
- cron: '0 5-22 * * *'
  branches: 
    include: 
    - azure-testcafe-test 
  always: true

variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

jobs:
- job: e2e_tests
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'
  - bash: echo "##vso[task.setvariable variable=yarnCacheDir;]$(yarn cache dir)"
    displayName: Set yarn cache dir variable
  - task: Cache@2
    inputs:
      key: 'yarn | "$(Agent.OS)" | yarn.lock'
      restoreKeys: |
        yarn | "$(Agent.OS)"
        yarn
      path: $(yarnCacheDir)
    displayName: Cache Yarn packages
  - script: |
        set -e
        export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
        node -v
        yarn -v
    displayName: "Print versions"
  - script: yarn --frozen-lockfile
    displayName: "Install dependencies"
  - script: yarn browser-test:azure
    displayName: 'Run TestCafe Tests'
    env:
      BROWSER_TESTS_ENV_URL: 'https://linkedcomponents-ui-dev.agw.arodevtest.hel.fi'
      BROWSER_TESTS_LINKED_EVENTS_URL: 'https://linkedevents-api.dev.hel.ninja/linkedevents-dev/v1'
      BROWSER_TESTS_SHOW_ADMIN: 'true'
      BROWSER_TESTS_SHOW_REGISTRATION: 'true'
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/report.xml'
      testResultsFormat: 'JUnit'
    condition: always()
