version: '3.7'

services:
  app:
    container_name: linkedcomponents-ui
    build:
      context: .
      target: ${DOCKER_TARGET:-development}
    env_file:
      - .env
      - .env.local
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:8000'
