# Don't allow dependencies to be used before they have been released for at least 1 week
minimumReleaseAge: 10080

# Exclude js-cookie 3.0.6 so we can apply the fix for the prototype hijack/cookie injection advisory immediately.
minimumReleaseAgeExclude:
  - js-cookie@3.0.6

# Don't warn about ignored build scripts
ignoredBuiltDependencies: []

# Hoist all dependencies to the root of node_modules, for better compatibility with packages that expect flat node_modules
shamefullyHoist: true

overrides:
  '@typescript-eslint/typescript-estree>minimatch': '>=9.0.7'
  'editorconfig>minimatch': '>=9.0.7'
  'hds-react>cookie': '0.7.2'
  'lodash': '>=4.18.1'
  'uuid': '>=11.1.1'

allowBuilds:
  '@ffmpeg-installer/darwin-arm64': true
  '@ffmpeg-installer/darwin-x64': true
  '@ffmpeg-installer/linux-x64': true
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  snyk: true
  unrs-resolver: true
