name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  common:
    uses: City-of-Helsinki/.github/.github/workflows/ci-pnpm-node.yml@feature/KEH-351-dependency-review-ci
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    with:
      node-version: 24
