name: Scheduled Production browser tests
on:
  schedule:
    # Every hour from 7 - 24 (finnish time winter time)
    - cron: '0 5-22 * * *'
#  uncomment the following if you want to develop this workflow in your own branch
#  push:
#    branches:
#      - TH-1047-scheduled-browser-tests
jobs:
  production-tests:
    name: Scheduled Acceptance tests against Production environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '14'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn --prefer-offline --frozen-lockfile --check-files --production=false
      - name: Run Acceptance Tests (TestCafe Browser Tests)
        id: testcafe
        run: yarn browser-test:ci
        env:
          BROWSER_TESTS_ENV_URL: https://linkedevents.hel.fi
          BROWSER_TESTS_LINKED_EVENTS_URL: 'https://api.hel.fi/linkedevents/v1'
          BROWSER_TESTS_SHOW_ADMIN: 'false'
          BROWSER_TESTS_SHOW_REGISTRATION: 'false'
          GITHUB_WORKFLOW_NAME: ${{ github.workflow }}
          GITHUB_WORKFLOW_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          TESTCAFE_SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          TESTCAFE_SLACK_CHANNEL: '#linked-alerts'
          TESTCAFE_SLACK_USERNAME: TestCafé
