name: Build & Production
on:
  push:
    tags:
      - 'release-*'

env:
  CONTAINER_REGISTRY: ghcr.io
  CONTAINER_REGISTRY_USER: ${{ secrets.GHCR_CONTAINER_REGISTRY_USER }}
  CONTAINER_REGISTRY_PASSWORD: ${{ secrets.GHCR_TOKEN }}
  CONTAINER_REGISTRY_REPO: ghcr.io/city-of-helsinki/${{ github.event.repository.name }}
  REPO_NAME: ${{ github.event.repository.name }}
  KUBECONFIG_RAW: ${{ secrets.KUBECONFIG_RAW_STABLE }}
  BUILD_ARTIFACT_FOLDER: 'build_artifacts'
  SERVICE_ARTIFACT_FOLDER: 'service_artifacts'
  SERVICE_PORT: 80
  K8S_REQUEST_CPU: 1m
  K8S_REQUEST_RAM: 10Mi
  K8S_LIMIT_CPU: 50m
  K8S_LIMIT_RAM: 20Mi
  K8S_REPLICACOUNT: 2

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: andersinno/kolga-build-action@v2
        env:
          DOCKER_IMAGE_NAME: ${{ env.REPO_NAME }}-production
          DOCKER_BUILD_ARG_PUBLIC_URL: 'https://linkedevents.hel.fi'
          DOCKER_BUILD_ARG_GENERATE_SITEMAP: 'true'
          DOCKER_BUILD_ARG_GENERATE_ROBOTS: 'true'
          DOCKER_BUILD_ARG_SASS_PATH: './src/assets/styles'
          DOCKER_BUILD_ARG_REACT_APP_LINKED_EVENTS_URL: 'https://api.hel.fi/linkedevents/v1'
          DOCKER_BUILD_ARG_REACT_APP_OIDC_AUTHORITY: 'https://api.hel.fi/sso'
          DOCKER_BUILD_ARG_REACT_APP_OIDC_CLIENT_ID: 'linkedcomponents-ui-prod'
          DOCKER_BUILD_ARG_REACT_APP_OIDC_SCOPE: 'openid profile https://api.hel.fi/auth/linkedevents'
          DOCKER_BUILD_ARG_REACT_APP_SENTRY_ENVIRONMENT: 'production'
          DOCKER_BUILD_ARG_REACT_APP_MATOMO_URL_BASE: '//webanalytics.digiaiiris.com/js/'
          DOCKER_BUILD_ARG_REACT_APP_MATOMO_SITE_ID: 223
          DOCKER_BUILD_ARG_REACT_APP_MATOMO_SRC_URL: 'piwik.min.js'
          DOCKER_BUILD_ARG_REACT_APP_MATOMO_TRACKER_URL: 'tracker.php'
          DOCKER_BUILD_ARG_REACT_APP_MATOMO_ENABLED: 'true'

  production:
    runs-on: ubuntu-latest
    needs: build
    name: Production
    steps:
      - uses: actions/checkout@v2
      - uses: andersinno/kolga-setup-action@v2

      - name: Deploy
        uses: andersinno/kolga-deploy-action@v2
        with:
          track: 'stable'
        env:
          K8S_NAMESPACE: ${{ secrets.K8S_NAMESPACE_STABLE }}
          K8S_ADDITIONAL_HOSTNAMES: ${{ secrets.K8S_ADDITIONAL_HOSTNAMES }}
          ENVIRONMENT_URL: https://${{ secrets.ENVIRONMENT_URL_STABLE }}
          DOCKER_IMAGE_NAME: ${{ env.REPO_NAME }}-production
