name: Build & Staging
on:
  push:
    branches:
      - develop

env:
  CONTAINER_REGISTRY: ghcr.io
  CONTAINER_REGISTRY_USER: ${{ secrets.GHCR_CONTAINER_REGISTRY_USER }}
  CONTAINER_REGISTRY_PASSWORD: ${{ secrets.GHCR_TOKEN }}
  CONTAINER_REGISTRY_REPO: ghcr.io/city-of-helsinki/${{ github.event.repository.name }}
  REPO_NAME: ${{ github.event.repository.name }}
  PUBLIC_URL: https://${{ secrets.ENVIRONMENT_URL_STAGING }}
  KUBECONFIG_RAW: ${{ secrets.KUBECONFIG_RAW_STAGING }}
  BUILD_ARTIFACT_FOLDER: 'build_artifacts'
  SERVICE_ARTIFACT_FOLDER: 'service_artifacts'
  SERVICE_PORT: 80
  K8S_REQUEST_CPU: 1m
  K8S_REQUEST_RAM: 10Mi
  K8S_LIMIT_CPU: 50m
  K8S_LIMIT_RAM: 20Mi
  K8S_REPLICACOUNT: 2

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Build
        # uses: andersinno/kolga-build-action@v2
        # https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-424
        uses: docker://ghcr.io/andersinno/kolga:2c6028bb7f478301d53928b0a72d5e87f58c0ac8-production
        with:
          entrypoint: /app/devops
          args: create_images
        env:
          DOCKER_IMAGE_NAME: ${{ env.REPO_NAME }}-staging
          DOCKER_BUILD_ARG_PUBLIC_URL: 'https://linkedcomponents-ui.test.kuva.hel.ninja'
          DOCKER_BUILD_ARG_GENERATE_SITEMAP: 'false'
          DOCKER_BUILD_ARG_SASS_PATH: './src/assets/styles'
          DOCKER_BUILD_ARG_REACT_APP_LINKED_EVENTS_URL: 'https://linkedevents-api.dev.hel.ninja/linkedevents-dev/v1'
          DOCKER_BUILD_ARG_REACT_APP_LINKED_REGISTRATIONS_UI_URL: 'https://linkedregistrations-ui.test.kuva.hel.ninja'
          DOCKER_BUILD_ARG_REACT_APP_OIDC_AUTHORITY: 'https://api.hel.fi/sso'
          DOCKER_BUILD_ARG_REACT_APP_OIDC_CLIENT_ID: 'linkedcomponents-ui-test'
          DOCKER_BUILD_ARG_REACT_APP_OIDC_SCOPE: 'openid profile email https://api.hel.fi/auth/linkedeventsdev'
          DOCKER_BUILD_ARG_REACT_APP_SENTRY_ENVIRONMENT: 'test'
          DOCKER_BUILD_ARG_REACT_APP_MATOMO_URL_BASE: 'https://analytics.hel.ninja/'
          DOCKER_BUILD_ARG_REACT_APP_MATOMO_SITE_ID: 69
          DOCKER_BUILD_ARG_REACT_APP_MATOMO_SRC_URL: 'matomo.js'
          DOCKER_BUILD_ARG_REACT_APP_MATOMO_TRACKER_URL: 'matomo.php'
          DOCKER_BUILD_ARG_REACT_APP_MATOMO_ENABLED: 'true'
          DOCKER_BUILD_ARG_REACT_APP_INTERNET_PLACE_ID: 'system:internet'
          DOCKER_BUILD_ARG_REACT_APP_LINKED_EVENTS_SYSTEM_DATA_SOURCE: 'helsinki'
          DOCKER_BUILD_ARG_REACT_APP_SHOW_ADMIN: 'true'
          DOCKER_BUILD_ARG_REACT_APP_SHOW_REGISTRATION: 'true'

  staging:
    runs-on: ubuntu-latest
    needs: build
    name: Staging + Acceptance tests
    steps:
      - uses: actions/checkout@v2
      - uses: andersinno/kolga-setup-action@v2

      - name: Deploy
        uses: andersinno/kolga-deploy-action@v2
        with:
          track: 'staging'
        env:
          K8S_NAMESPACE: ${{ secrets.K8S_NAMESPACE_STAGING }}
          ENVIRONMENT_URL: https://${{ secrets.ENVIRONMENT_URL_STAGING }}
          DOCKER_IMAGE_NAME: ${{ env.REPO_NAME }}-staging
      - name: Staging deploy notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: Deployer
          SLACK_ICON: https://a.slack-edge.com/80588/img/services/outgoing-webhook_48.png
          SLACK_TITLE: ${{ env.PUBLIC_URL }} has been updated!
          SLACK_MESSAGE: 'A new version of Linked Events UI has been deployed to staging! :tada: :tada: '
          SLACK_CHANNEL: linked-alerts
        if: success()
      - name: Staging deploy failure notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: Deployer
          SLACK_ICON: https://a.slack-edge.com/80588/img/services/outgoing-webhook_48.png
          SLACK_TITLE: Deploying to ${{ env.PUBLIC_URL }} has *FAILED!*
          SLACK_MESSAGE: Deploying to ${{ env.PUBLIC_URL }} has *FAILED!*
          SLACK_CHANNEL: linked-alerts
        if: failure()
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '14'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn --prefer-offline --frozen-lockfile --check-files --production=false
      - name: Run TestCafe tests for https://linkedcomponents-ui.test.kuva.hel.ninja
        id: testcafe
        run: yarn browser-test:ci
        env:
          BROWSER_TESTS_ENV_URL: https://${{ secrets.ENVIRONMENT_URL_STAGING }}
          BROWSER_TESTS_LINKED_EVENTS_URL: 'https://linkedevents-api.dev.hel.ninja/linkedevents-dev/v1'
          BROWSER_TESTS_SHOW_ADMIN: 'true'
          BROWSER_TESTS_SHOW_REGISTRATION: 'true'
          GITHUB_WORKFLOW_NAME: ${{  github.workflow }}
          GITHUB_WORKFLOW_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          TESTCAFE_SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          TESTCAFE_SLACK_CHANNEL: '#linked-alerts'
          TESTCAFE_SLACK_USERNAME: TestCafé
      - name: Upload screenshots and videos of failed tests to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: report/
        if: always() && steps.testcafe.outcome == 'failure'
