name: Build & Staging
on:
  push:
    branches:
      - develop

env:
  CONTAINER_REGISTRY: ghcr.io
  CONTAINER_REGISTRY_USER: ${{ secrets.GHCR_CONTAINER_REGISTRY_USER }}
  CONTAINER_REGISTRY_PASSWORD: ${{ secrets.GHCR_TOKEN }}
  CONTAINER_REGISTRY_REPO: ghcr.io/city-of-helsinki/${{ github.event.repository.name }}
  REPO_NAME: ${{ github.event.repository.name }}
  KUBECONFIG_RAW: ${{ secrets.KUBECONFIG_RAW_STAGING }}
  BUILD_ARTIFACT_FOLDER: 'build_artifacts'
  SERVICE_ARTIFACT_FOLDER: 'service_artifacts'
  SERVICE_PORT: 80
  K8S_REQUEST_CPU: 1m
  K8S_REQUEST_RAM: 10Mi
  K8S_LIMIT_CPU: 50m
  K8S_LIMIT_RAM: 20Mi
  K8S_REPLICACOUNT: 2

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: andersinno/kolga-build-action@v2
        env:
          DOCKER_IMAGE_NAME: ${{ env.REPO_NAME }}-staging
          DOCKER_BUILD_ARG_PUBLIC_URL: 'https://linkedcomponents-ui.test.kuva.hel.ninja'
          DOCKER_BUILD_ARG_GENERATE_SITEMAP: 'false'
          DOCKER_BUILD_ARG_SASS_PATH: './src/assets/styles'
          DOCKER_BUILD_ARG_REACT_APP_LINKED_EVENTS_URL: 'https://linkedevents-api.dev.hel.ninja/linkedevents-dev/v1'
          DOCKER_BUILD_ARG_REACT_APP_OIDC_AUTHORITY: 'https://api.hel.fi/sso'
          DOCKER_BUILD_ARG_REACT_APP_OIDC_CLIENT_ID: 'linkedcomponents-ui-test'
          DOCKER_BUILD_ARG_REACT_APP_OIDC_SCOPE: 'openid profile email https://api.hel.fi/auth/linkedeventsdev'
          DOCKER_BUILD_ARG_REACT_APP_SENTRY_ENVIRONMENT: 'test'
          DOCKER_BUILD_ARG_REACT_APP_MATOMO_URL_BASE: 'https://analytics.hel.ninja/'
          DOCKER_BUILD_ARG_REACT_APP_MATOMO_SITE_ID: 69
          DOCKER_BUILD_ARG_REACT_APP_MATOMO_SRC_URL: 'matomo.js'
          DOCKER_BUILD_ARG_REACT_APP_MATOMO_TRACKER_URL: 'matomo.php'
          DOCKER_BUILD_ARG_REACT_APP_MATOMO_ENABLED: 'true'

  staging:
    runs-on: ubuntu-latest
    needs: build
    name: Staging
    steps:
      - uses: actions/checkout@v2
      - uses: andersinno/kolga-setup-action@v2

      - name: Deploy
        uses: andersinno/kolga-deploy-action@v2
        with:
          track: 'staging'
        env:
          K8S_NAMESPACE: ${{ secrets.K8S_NAMESPACE_STAGING }}
          ENVIRONMENT_URL: https://${{ secrets.ENVIRONMENT_URL_STAGING }}
          DOCKER_IMAGE_NAME: ${{ env.REPO_NAME }}-staging
